# Generated by Django 4.0 on 2022-02-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0002_ether_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ether',
            name='balance',
            field=models.FloatField(),
        ),
    ]
